spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://114.132.43.99:3306/testdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testdb
    password: GrsSecjFYKFkfKwY

# mybatis 配置
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 Mybatis 配置文件路径
  # mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: org.springframework.springboot.lab.mybatis.annotation.dataobject #