spring:
  datasource:
    url: jdbc:mysql://192.168.110.100:3380/security-dynamic-management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
