server:
  port: 9005
  servlet:
    context-path: /redis-cache-breakdown


spring:
  swagger2:
    enabled: true
  redis:
    host: 192.168.110.100
    timeout: 3000   # 连接语句
    lettuce:
      pool:
        max-active: 20   # 最大连接数
        min-idle: 5      # 最小空闲
        max-wait: 5000ms # 连接超时
        max-idle: 20     # 最大空闲


