spring:
  # 对应 RedisProperties 类
  redis:
    host: 114.132.43.99
    port: 6379
    password: XMG8bNjf2Yc3EQaYPYcJVe58 # Redis 服务器密码, 默认为空。生产环境中必须要设置
    database: 0 # Redis 数据库号。默认为 0
    timeout: 0 # Redis 连接超时时间, 单位: 毫秒
    # 对应 RedissonProperties 类
    # redisson:
    #   config: classpath:redisson.yml # 具体的每个配置项，见 org.redisson.config.Config 类。
