server:
  port: 9009
  servlet:
    context-path: /j2cache

rainbow:
  redis:
    host: 192.168.110.100
    port: 6379
    password:
    database: 0

spring:
  redis:
    host: ${rainbow.redis.host}
    password: ${rainbow.redis.password}
    port: ${rainbow.redis.port}
    database: ${rainbow.redis.database}

j2cache:
  cache-clean-mode: passive
  allow-null-values: true
  redis-client: lettuce  # 指定 redis 客户端为 lettuce, 也可以设置为 jedis
  l2-cache-open: true # 开启二级缓存
  broadcast: net.oschina.j2cache.cache.support.redis.SpringRedisPubSubPolicy
  L1:
    provider_class: caffeine
  L2:
    provider_class: net.oschina.j2cache.cache.support.redis.SpringRedisProvider
    config_section: lettuce
  sync_ttl_to_redis: true
  default_cache_null_object: false
  serialization: fst  #序列化方式：fst、kyro、Java

caffeine:
  properties: /caffeine.properties
lettuce:
  mode: single
  namespace:
  storage: generic
  channel: j2cache
  scheme: redis
  hosts: ${rainbow.redis.host}:${rainbow.redis.port}
  password: ${rainbow.redis.password}
  sentinelMasterId:
  maxTotal: 100
  maxIdle: 10
  minIdle: 10
  timeout: 10000


